baseURL = 'https://pinggirjurangstudio.github.io/'
languageCode = 'en-us'
title = 'Pinggir Jurang Studio'

[module]
  [[module.imports]]
    path = 'github.com/HEIGE-PCloud/DoIt'

[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'